### ISSUE TITLE
K590s i5版本 黑苹果安装问题

### ISSUE THREAD

**Issue by Largercode** [whidy/W350ETQ-Clover#2]
首先感谢分享，我的是k590s i5版本的，理论和你的只是cpu有区别。第一次选第二个图标图标屏蔽独显进去选择盘安装，第二次进去选第三个图标屏蔽独显进入安装，等一会出现安装剩余22分钟，然后就屏幕打印一些输出，接着就黑屏了，请问有遇到这种情况么？谢谢。

**Comment by whidy** [comment]
建议先移除我的dsdt补丁, 进行安装... 安装成功后再用那个工具去生成对应的cpu 补丁
