### ISSUE TITLE
你的外置显示器能用么?

### ISSUE THREAD

**Issue by JokerHYC** [whidy/W350ETQ-Clover#3]
我装了mojave 然后能够驱动hd4000显卡 但是外接显示器八个苹果了
你的可以外接么?
对了 我的cpu是3630qm 和你的不一样啊

**Comment by whidy** [comment]
**我的是可以外接的**，不过我用的是文中提到的10.13版，没有尝试过10.14所以无法给你准确的回复。

外接跟CPU一般没有关系，当然你感觉睿频不正确等问题，你可以使用我说明文档提到的[ssdtPRGen.sh](https://github.com/Piker-Alpha/ssdtPRGen.sh)来patch。

你说的8个苹果试啥样的。。。我没遇到过。当然无法外屏的原因也有可能还是clover的config上面的patch存在问题。你可以参考：

* [OS-X-Clover-Laptop-Config](https://github.com/RehabMan/OS-X-Clover-Laptop-Config)
* [[Guide] Booting the OS X installer on LAPTOPS with Clover](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/)

**Comment by JokerHYC** [comment]
好的,谢谢.
既然你可以我就继续尝试吧.
